//Users
const users = [
  {
    username: "jdoe1",
    email: "jdoe1@example.com",
    password: "P@ssw0rd123",
    firstname: "John",
    lastname: "Doakis",
    birthdate: "1990-05-14",
    gender: "male",
    country: "Greece",
    city: "Heraklion",
    address: "Pl. Kiprou 5",
    telephone: "+30 2810 123456",
    lat: 35.3332276,
    lon: 25.1162213
  },
  {
    username: "asmith2",
    email: "asmith2@example.com",
    password: "Str0ngPass!",
    firstname: "Alice",
    lastname: "Papadaki",
    birthdate: "1985-08-23",
    gender: "female",
    country: "Greece",
    city: "Heraklion",
    address: "CSD Voutes",
    telephone: "+30 2810 654321",
    lat: 35.3053121,
    lon: 25.0722869
  },
  {
    username: "mnikos3",
    email: "mnikos3@example.com",
    password: "Nik0sPass#",
    firstname: "Nikos",
    lastname: "Makris",
    birthdate: "1992-01-12",
    gender: "male",
    country: "Greece",
    city: "Heraklion",
    address: "Dimokratias 99",
    telephone: "+30 2810 777888",
    lat: 35.3401097,
    lon: 25.1562301
  },
  {
    username: "eleni4",
    email: "eleni4@example.com",
    password: "3leniS3cret",
    firstname: "Eleni",
    lastname: "Pappa",
    birthdate: "1995-11-30",
    gender: "female",
    country: "Greece",
    city: "Chersonisos",
    address: "Limenas Chersonisou",
    telephone: "+30 2810 998877",
    lat: 35.318761,
    lon: 25.3715371
  },
  {
    username: "gsarris5",
    email: "gsarris5@example.com",
    password: "Pass@2025",
    firstname: "Giorgos",
    lastname: "Sarris",
    birthdate: "1988-07-09",
    gender: "male",
    country: "Greece",
    city: "Heraklion",
    address: "77 Kalokairinou Ave",
    telephone: "+30 2810 111222",
    lat: 35.3383846,
    lon: 25.1275827
  },
  {
    username: "mariachania",
    email: "maria.chania@example.com",
    password: "Mari@1234",
    firstname: "Maria",
    lastname: "Kefalogianni",
    birthdate: "1993-03-21",
    gender: "female",
    country: "Greece",
    city: "Chania",
    address: "Apostolidou 20",
    telephone: "+30 2821 445566",
    lat: 35.5383431,
    lon: 23.9755019
  },
  {
    username: "panoschania",
    email: "panos@example.com",
    password: "PanosSecure9",
    firstname: "Panos",
    lastname: "Lykos",
    birthdate: "1987-10-17",
    gender: "male",
    country: "Greece",
    city: "Chania",
    address: "88 Apokoronou St",
    telephone: "+30 2821 334455",
    lat: 35.5098241,
    lon: 24.0198088
  },
  {
    username: "eirinireth",
    email: "eirini@example.com",
    password: "eirini2025!",
    firstname: "Eirini",
    lastname: "Kontou",
    birthdate: "1998-04-03",
    gender: "female",
    country: "Greece",
    city: "Rethymnon",
    address: "45 Arkadiou St",
    telephone: "+30 2831 667788",
    lat: 35.3669844,
    lon: 24.4601031
  },
  {
    username: "steliosreth",
    email: "stelios@example.com",
    password: "St3li0s@123",
    firstname: "Stelios",
    lastname: "Tzoumakas",
    birthdate: "1991-06-15",
    gender: "male",
    country: "Greece",
    city: "Rethymnon",
    address: "101 Eleftheriou Venizelou",
    telephone: "+30 2831 556677",
    lat: 35.3697727,
    lon: 24.4583494
  },
  {
    username: "dimitraiera",
    email: "dimitra@example.com",
    password: "Dim1tra!pass",
    firstname: "Dimitra",
    lastname: "Argyri",
    birthdate: "1996-09-29",
    gender: "female",
    country: "Greece",
    city: "Ierapetra",
    address: "Kalimeraki 34",
    telephone: "+30 2842 334455",
    lat: 35.0133561,
    lon: 25.7370137
  },
  {
    username: "admin",
    email: "admin@test.com",
    password: "admiN12@*",   // Προσοχή: your DB stores MD5?, bcrypt?
    firstname: "Admin",
    lastname: "SuperUser",
    birthdate: "1980-01-01",
    gender: "Άλλο",
    country: "Greece",
    city: "Athens",
    address: "Admin Street",
    telephone: "2100000000",
    lat: null,
    lon: null
}

];

const bands=[
  {
    "band_id": 1,
    "username": "cretanwaves",
    "email": "info@cretanwaves.gr",
    "password": "hashed_pw_1",
    "band_name": "Cretan Waves",
    "music_genres": "Indie Rock",
    "band_description": "An indie rock band blending modern sounds with Cretan traditional rhythms.",
    "members_number": 5,
    "foundedYear": 2012,
    "band_city": "Heraklion",
    "telephone": "+30 2810 123456",
    "webpage": "https://cretanwaves.gr",
    "photo": "cretanwaves.jpg"
  },
  {
    "band_id": 2,
    "username": "chaniafolk",
    "email": "contact@chaniafolkband.gr",
    "password": "hashed_pw_2",
    "band_name": "Chania Folk Ensemble",
    "music_genres": "Folk, Traditional",
    "band_description": "Preserving and modernizing the folk music of western Crete.",
    "members_number": 7,
    "foundedYear": 2005,
    "band_city": "Chania",
    "telephone": "+30 2821 234567",
    "webpage": "https://chaniafolkband.gr",
    "photo": "chaniafolk.jpg"
  },
  {
    "band_id": 3,
    "username": "rethymnojazz",
    "email": "jazz@rethymnojazz.gr",
    "password": "hashed_pw_3",
    "band_name": "Rethymno Jazz Collective",
    "music_genres": "Jazz, Fusion",
    "band_description": "A smooth blend of Mediterranean jazz and fusion improvisations.",
    "members_number": 6,
    "foundedYear": 2010,
    "band_city": "Rethymno",
    "telephone": "+30 2831 345678",
    "webpage": "https://rethymnojazz.gr",
    "photo": "rethymnojazz.jpg"
  },
  {
    "band_id": 4,
    "username": "minotaurmetal",
    "email": "metal@minotaurmetal.gr",
    "password": "hashed_pw_4",
    "band_name": "Minotaur Metal",
    "music_genres": "Heavy Metal",
    "band_description": "A powerful metal band inspired by Cretan mythology and legends.",
    "members_number": 4,
    "foundedYear": 2016,
    "band_city": "Heraklion",
    "telephone": "+30 2810 654321",
    "webpage": "https://minotaurmetal.gr",
    "photo": "minotaurmetal.jpg"
  },
  {
    "band_id": 5,
    "username": "aegeansoul",
    "email": "hello@aegeansoul.gr",
    "password": "hashed_pw_5",
    "band_name": "Aegean Soul",
    "music_genres": "Soul, Pop",
    "band_description": "Smooth soul-pop melodies inspired by the Aegean breeze.",
    "members_number": 5,
    "foundedYear": 2018,
    "band_city": "Agios Nikolaos",
    "telephone": "+30 2841 223344",
    "webpage": "https://aegeansoul.gr",
    "photo": "aegeansoul.jpg"
  },
  {
    "band_id": 6,
    "username": "sitiafunk",
    "email": "info@sitiafunk.gr",
    "password": "hashed_pw_6",
    "band_name": "Sitia Funk Syndicate",
    "music_genres": "Funk, Groove",
    "band_description": "Groovy rhythms and brass-powered funk from eastern Crete.",
    "members_number": 6,
    "foundedYear": 2014,
    "band_city": "Sitia",
    "telephone": "+30 2843 556677",
    "webpage": "https://sitiafunk.gr",
    "photo": "sitiafunk.jpg"
  },
  {
    "band_id": 7,
    "username": "lyraelectrica",
    "email": "contact@lyraelectrica.gr",
    "password": "hashed_pw_7",
    "band_name": "Lyra Electrica",
    "music_genres": "Electronic, World",
    "band_description": "Fusing electronic beats with the Cretan lyra and world sounds.",
    "members_number": 3,
    "foundedYear": 2017,
    "band_city": "Heraklion",
    "telephone": "+30 2810 778899",
    "webpage": "https://lyraelectrica.gr",
    "photo": "lyraelectrica.jpg"
  },
  {
    "band_id": 8,
    "username": "mountainblues",
    "email": "info@mountainblues.gr",
    "password": "hashed_pw_8",
    "band_name": "Mountain Blues Band",
    "music_genres": "Blues, Rock",
    "band_description": "Authentic blues-rock with a Cretan mountain spirit.",
    "members_number": 5,
    "foundedYear": 2009,
    "band_city": "Rethymno",
    "telephone": "+30 2831 556677",
    "webpage": "https://mountainblues.gr",
    "photo": "mountainblues.jpg"
  },
  {
    "band_id": 9,
    "username": "cretebeats",
    "email": "beats@cretebeats.gr",
    "password": "hashed_pw_9",
    "band_name": "Crete Beats",
    "music_genres": "Electronic, House",
    "band_description": "DJ collective producing house and techno events all around Crete.",
    "members_number": 4,
    "foundedYear": 2020,
    "band_city": "Heraklion",
    "telephone": "+30 2810 667788",
    "webpage": "https://cretebeats.gr",
    "photo": "cretebeats.jpg"
  },
  {
    "band_id": 10,
    "username": "chaniachoir",
    "email": "choir@chaniachoir.gr",
    "password": "hashed_pw_10",
    "band_name": "Chania Voices",
    "music_genres": "Choral, Classical",
    "band_description": "A modern choir performing classical and Cretan compositions.",
    "members_number": 25,
    "foundedYear": 2002,
    "band_city": "Chania",
    "telephone": "+30 2821 998877",
    "webpage": "https://chaniachoir.gr",
    "photo": "chaniachoir.jpg"
  },
  {
    "band_id": 11,
    "username": "eastwind",
    "email": "eastwind@sitia.gr",
    "password": "hashed_pw_11",
    "band_name": "East Wind",
    "music_genres": "Progressive Rock",
    "band_description": "A progressive rock band inspired by Cretan landscapes.",
    "members_number": 5,
    "foundedYear": 2011,
    "band_city": "Sitia",
    "telephone": "+30 2843 334455",
    "webpage": "https://eastwind.gr",
    "photo": "eastwind.jpg"
  },
  {
    "band_id": 12,
    "username": "melissasound",
    "email": "melissa@melissasound.gr",
    "password": "hashed_pw_12",
    "band_name": "Melissa Sound",
    "music_genres": "Pop, Indie",
    "band_description": "Pop melodies with Cretan poetic influences.",
    "members_number": 4,
    "foundedYear": 2015,
    "band_city": "Agios Nikolaos",
    "telephone": "+30 2841 667788",
    "webpage": "https://melissasound.gr",
    "photo": "melissasound.jpg"
  },
  {
    "band_id": 13,
    "username": "nereids",
    "email": "info@nereidsband.gr",
    "password": "hashed_pw_13",
    "band_name": "Nereids",
    "music_genres": "Alternative, Dream Pop",
    "band_description": "Dreamy soundscapes and ethereal vocals inspired by the sea nymphs.",
    "members_number": 5,
    "foundedYear": 2019,
    "band_city": "Rethymno",
    "telephone": "+30 2831 221100",
    "webpage": "https://nereidsband.gr",
    "photo": "nereids.jpg"
  },
  {
    "band_id": 14,
    "username": "southgroove",
    "email": "groove@southgroove.gr",
    "password": "hashed_pw_14",
    "band_name": "South Groove",
    "music_genres": "Reggae, Funk",
    "band_description": "Southern Cretan vibes mixed with reggae rhythms and funky beats.",
    "members_number": 6,
    "foundedYear": 2013,
    "band_city": "Ierapetra",
    "telephone": "+30 2842 443322",
    "webpage": "https://southgroove.gr",
    "photo": "southgroove.jpg"
  },
  {
    "band_id": 15,
    "username": "cretanstrings",
    "email": "info@cretanstrings.gr",
    "password": "hashed_pw_15",
    "band_name": "Cretan Strings",
    "music_genres": "Traditional, Acoustic",
    "band_description": "Acoustic ensemble preserving the art of lyra and laouto.",
    "members_number": 3,
    "foundedYear": 2008,
    "band_city": "Heraklion",
    "telephone": "+30 2810 778800",
    "webpage": "https://cretanstrings.gr",
    "photo": "cretanstrings.jpg"
  },
  {
    "band_id": 16,
    "username": "chaniaalt",
    "email": "alt@chaniaaltband.gr",
    "password": "hashed_pw_16",
    "band_name": "Chania Alt Scene",
    "music_genres": "Alternative Rock",
    "band_description": "Alternative rockers shaping the sound of Chania’s underground scene.",
    "members_number": 5,
    "foundedYear": 2016,
    "band_city": "Chania",
    "telephone": "+30 2821 555333",
    "webpage": "https://chaniaaltband.gr",
    "photo": "chaniaalt.jpg"
  },
  {
    "band_id": 17,
    "username": "cretasymphony",
    "email": "info@cretasymphony.gr",
    "password": "hashed_pw_17",
    "band_name": "Creta Symphony",
    "music_genres": "Classical, Orchestral",
    "band_description": "Regional symphony orchestra based in Heraklion performing across Crete.",
    "members_number": 4,
    "foundedYear": 1998,
    "band_city": "Heraklion",
    "telephone": "+30 2810 112233",
    "webpage": "https://cretasymphony.gr",
    "photo": "cretasymphony.jpg"
  },
  {
    "band_id": 18,
    "username": "blueharbor",
    "email": "contact@blueharbor.gr",
    "password": "hashed_pw_18",
    "band_name": "Blue Harbor",
    "music_genres": "Soft Rock",
    "band_description": "Soft rock band inspired by the harbors of western Crete.",
    "members_number": 4,
    "foundedYear": 2010,
    "band_city": "Chania",
    "telephone": "+30 2821 777999",
    "webpage": "https://blueharbor.gr",
    "photo": "blueharbor.jpg"
  },
  {
    "band_id": 19,
    "username": "sunsetproject",
    "email": "sunset@sunsetproject.gr",
    "password": "hashed_pw_19",
    "band_name": "Sunset Project",
    "music_genres": "Electronic, Chillout",
    "band_description": "Electronic chillout duo performing at Crete’s beach festivals.",
    "members_number": 2,
    "foundedYear": 2021,
    "band_city": "Agios Nikolaos",
    "telephone": "+30 2841 555666",
    "webpage": "https://sunsetproject.gr",
    "photo": "sunsetproject.jpg"
  },
  {
    "band_id": 20,
    "username": "ierapetrarockers",
    "email": "rock@ierapetrarockers.gr",
    "password": "hashed_pw_20",
    "band_name": "Ierapetra Rockers",
    "music_genres": "Rock, Blues",
    "band_description": "A passionate local rock band known for powerful live shows.",
    "members_number": 5,
    "foundedYear": 2007,
    "band_city": "Ierapetra",
    "telephone": "+30 2842 556677",
    "webpage": "https://ierapetrarockers.gr",
    "photo": "ierapetrarockers.jpg"
  }
]

const public_events=[
  {
    "band_id": 1,
    "event_type": "Live Concert",
    "event_description": "Indie rock night by the sea.",
    "event_datetime": "2026-01-10T20:00:00",
    "participants_price": 15.0,
    "event_city": "Heraklion",
    "event_address": "Talos Plaza",
    "event_lat": 35.3406733,
    "event_lon": 25.1016577
  },
  {
    "band_id": 2,
    "event_type": "Folk Night",
    "event_description": "Folk evening in the old town square.",
    "event_datetime": "2026-01-17T21:00:00",
    "participants_price": 12.0,
    "event_city": "Chania",
    "event_address": "Akti Tompazi 5",
    "event_lat": 35.5180551,
    "event_lon": 24.0157043
  },
  {
    "band_id": 3,
    "event_type": "Jazz Session",
    "event_description": "Jazz Night",
    "event_datetime": "2026-01-24T19:30:00",
    "participants_price": 10.0,
    "event_city": "Rethymno",
    "event_address": "Sofokli Venizelou 25",
    "event_lat": 35.3665448,
    "event_lon": 24.4808939
  },
  {
    "band_id": 1,
    "event_type": "Live Concert",
    "event_description": "Indie rock night by the sea.",
    "event_datetime": "2026-01-31T22:00:00",
    "participants_price": 18.0,
    "event_city": "Heraklion",
    "event_address": "Liberty Square",
    "event_lat": 35.3377782,
    "event_lon": 25.1178919
  },
  {
    "band_id": 5,
    "event_type": "Soft rock Concert",
    "event_description": "Fundraiser for local shelters with soft-rock music.",
    "event_datetime": "2026-02-02T20:00:00",
    "participants_price": 12.0,
    "event_city": "Chania",
    "event_address": "Municipal Market, Platia Agora",
    "event_lat": 35.5142989,
    "event_lon": 24.0171743
  }
]

const reviews=[
  {
    "band_name": "Cretan Waves",
    "sender": "Stefanos Tsitsipas",
    "review": "Amazing live performance! The band had great energy and connected really well with the audience.",
    "rating": 5,
    "date_time": "2026-02-01T22:15:00",
    "status": "published"
  },
  {
    "band_name": "Chania Folk Ensemble",
    "sender": "mike",
    "review": "Loved the acoustic session — beautiful vocals and atmosphere. Would definitely attend again!",
    "rating": 5,
    "date_time": "2026-02-05T19:45:00",
    "status": "published"
  },
  {
    "band_name": "Minotaur Metal",
    "sender": "qwerty",
    "review": "Great initiative with the charity concert, but the sound quality could have been better.",
    "rating": 4,
    "date_time": "2026-02-07T09:20:00",
    "status": "pending"
  }
]

const private_events=
[
  {
    "band_id": 1,
    "price": 1000.0,
    "status": "requested",
    "band_decision": "",
    "user_id": 1,
    "event_type": "Wedding",
     "event_datetime": "2026-05-18T21:00:00",
    "event_description": "Live wedding performance for three hours",
    "event_city": "Heraklion",
    "event_address": "Olympia Palace",
    "event_lat": 35.3437533,
    "event_lon": 25.0286834
  },
  {
    "band_id": 2,
    "price": 500.0,
    "status": "to be done",
    "band_decision": "Accepted, for that date,",
    "user_id": 6,
    "event_type": "Party",
     "event_datetime": "2026-02-27T21:00:00",
    "event_description": "Private birthday party with 80s rock music.",
   
    "event_city": "Chania",
    "event_address": "Cafe Remezzo",
    "event_lat": 35.5168076,
    "event_lon": 24.0152191
  },
  {
    "band_id": 7,
    "price": 750.0,
    "status": "done",
    "band_decision": "Glad to play for the baptism",
    "user_id": 2,
    "event_type": "Baptism",
    "event_datetime": "2025-03-09T13:30:00",
    "event_description": "Cretan traditional music for a baptism reception.",
    
    "event_city": "Heraklion",
    "event_address": "Anadromes",
    "event_lat": 35.2476282,
    "event_lon": 25.1659937
  }
]

const messages=[
  {
    "private_event_id": 1,
    "message": "Hi, just confirming that the band will arrive one hour before the party starts for setup.",
    "sender": "band",
    "recipient": "user",
    "date_time": "2025-11-11T10:15:00"
  },
  {
    "private_event_id": 1,
    "message": "Perfect, thank you! The party starts at 9 PM, so setup at 8 PM is great.",
    "sender": "user",
    "recipient": "band",
    "date_time": "2026-11-11T11:05:00"
  },
  {
    "private_event_id": 1,
    "message": "We’ll bring all sound equipment, just ensure power access near the stage area.",
    "sender": "band",
    "recipient": "user",
    "date_time": "2026-11-11T18:40:00"
  }
]


module.exports = {users, bands,public_events, reviews,private_events, messages};